name: DG Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 每 5 分钟运行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install selenium pillow requests opencv-python pytz

      - name: 运行 DG 监控
        run: python dg_monitor.py
