name: DG Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟执行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium opencv-python-headless numpy pytz

      - name: 执行 DG 监控
        run: python monitor.py
