name: DG Baccarat Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟检测一次

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 防止GitHub Actions 6小时限制
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright==1.39.0
          playwright install chromium

      - name: Run DG Monitor Script
        run: python monitor.py
