name: DG Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pytz

      - name: Run DG Monitor
        run: python dg_monitor.py
