name: DG Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟执行一次
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install --with-deps

      - name: Run DG Monitor
        run: |
          python dg_monitor.py
