name: DG Baccarat Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次
  workflow_dispatch:       # 支持手动启动

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install requests selenium opencv-python pytz numpy

      - name: 执行放水监测
        run: python monitor.py
