name: DG Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # 每5分钟自动执行一次

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium opencv-python numpy pytz

      - name: 运行 DG 监控
        run: |
          python monitor.py
